services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    volumes:
      - ha_config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    network_mode: host
    devices:
      # Make sure this matched your adapter location
      - /dev/ttyUSB0:/dev/ttyUSB0

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    depends_on:
      - eclipse_mosquitto
    privileged: true
    volumes:
      - zigbee2mqtt_data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 55403:8080
    environment:
      - TZ=Asia/Japan
    devices:
      # Make sure this matched your adapter location
      - /dev/ttyUSB0:/dev/ttyUSB0

  eclipse_mosquitto:
    container_name: eclipse_mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    volumes:
      - mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    network_mode: host
    environment:
      - TZ=Asia/Japan

volumes:
  ha_config:
  zigbee2mqtt_data:
  mosquitto_config:
  mosquitto_data:
  mosquitto_log:
