apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: clusterissuer-le
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: davafons@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - selector:
          dnsZones:
            - davafons.com
            - "*.davafons.com"
            - brigadasos.xyz
            - "*.brigadasos.xyz"
        dns01:
          cloudflare:
            email: davafons@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
