kind: PersistentVolume
apiVersion: v1
metadata:
  name: mylar3-komga-pv
  labels:
    type: local
    app: mylar3
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/media/komga"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mylar3-komga-pv-claim
  labels:
    app: mylar3
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mylar3-import-pv
  labels:
    type: local
    app: mylar3
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/media/import"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mylar3-import-pv-claim
  labels:
    app: mylar3
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mylar3-config-pv-claim
  labels:
    app: mylar3
spec:
  storageClassName: local-path
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mylar3
  namespace: mylar3
spec:
  selector:
   matchLabels:
    app: mylar3
  replicas: 1
  template:
    metadata:
      labels:
        app: mylar3
    spec:
      containers:
        - name: mylar3
          image: lscr.io/linuxserver/mylar3:latest
          ports:
            - containerPort: 8090
          volumeMounts:
          - mountPath: /comics
            name: mylar3-komga-pv-vol
          - mountPath: /downloads
            name: mylar3-import-pv-vol
          - mountPath: /config
            name: mylar3-config-pv-vol
      volumes:
        - name: mylar3-komga-pv-vol
          persistentVolumeClaim:
            claimName: mylar3-komga-pv-claim
        - name: mylar3-import-pv-vol
          persistentVolumeClaim:
            claimName: mylar3-import-pv-claim
        - name: mylar3-config-pv-vol
          persistentVolumeClaim:
            claimName: mylar3-config-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mylar3-service
  namespace: mylar3
  labels:
    app: mylar3
spec:
  selector:
    app: mylar3
  ports:
   - port: 8090
     protocol: TCP
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mylar3-cert
  namespace: mylar3
spec:
  secretName: certificate-mylar3
  dnsNames:
    - mylar3.davafons.com
  issuerRef:
    name: clusterissuer-le
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mylar3-ingress
  namespace: mylar3
  labels:
    app: mylar3
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: clusterissuer-le
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mylar3.davafons.com
      secretName: certificate-mylar3
  rules:
    - host: mylar3.davafons.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: mylar3-service
                port:
                  number: 8090