version: "3.8"
services:
  wg-easy:
    environment:
      - WG_HOST=${WG_HOST}

      # Optional:
      - PASSWORD=${PASSWORD}
      - WG_PORT=${WG_PORT}
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS}
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS}

    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    network_mode: bridge
    volumes:
      - wg_config:/etc/wireguard
    ports:
      - "${WG_PORT}:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - syncthing_config:/config
      - /share:/sync
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

volumes:
  wg_config:
  syncthing_config:
