services:
  pia-qbittorrent:
    image: j4ym0/pia-qbittorrent
    container_name: pia-qbittorrent
    restart: unless-stopped
    cap_add:
        - NET_ADMIN
    environment:
        - UID=1000
        - GID=100
        - REGION=Japan
        - USER=${PIA_USER}
        - PASSWORD=${PIA_PASSWORD}
        - PORT_FORWARDING=true
        - LEGACY_IPTABLES=true
        - TZ=Asia/Tokyo
    volumes:
        - /share/appdata/qbittorrent-vpn-pia:/config
        - /share/Download:/downloads
    ports:
        - 8888:8888
    networks:
      - qbittorrent-pia-vpn_default

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - sonarr:/config
      - /share/Media/Series:/tv
      - /share/Download:/downloads
    networks:
      - qbittorrent-pia-vpn_default

volumes:
  sonarr:
    external: true

networks:
  qbittorrent-pia-vpn_default:
    external: true