services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - sonarr:/config
      - /share/Download:/tv
      - /share/Media/Series:/downloads
    networks:
      - qbittorrent-pia-vpn_default

volumes:
  sonarr:
    external: true

networks:
  qbittorrent-pia-vpn_default:
    external: true