services:
  pia-qbittorrent:
    image: j4ym0/pia-qbittorrent
    container_name: pia-qbittorrent
    ports:
        - 8888:8888
    cap_add:
      - NET_ADMIN
    environment:
      - REGION=Japan
      - USER=${PIA_USER}
      - PASSWORD=${PIA_PASSWORD}
      - PORT_FORWARDING=true
      - LEGACY_IPTABLES=true
      - TZ=Asia/Tokyo
    volumes:
      - qbittorrent:/config
      - qbittorrent_etc:/etc
      - /share/Download:/downloads

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    depends_on:
      - pia-qbittorrent
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - sonarr:/config
      - /share/Media/Series:/tv
      - /share/Download:/downloads

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    depends_on:
      - pia-qbittorrent
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - radarr:/config
      - /share/Media/Movies:/movies
      - /share/Download:/downloads

  bazarr:
    image: lscr.io/linuxserver/bazarr:development
    container_name: bazarr
    restart: unless-stopped
    depends_on:
      - pia-qbittorrent
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - bazarr:/config
      - /share/Media/Movies:/movies
      - /share/Media/Series:/tv
      - /share/Download:/downloads

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    depends_on:
      - pia-qbittorrent
    ports:
      - 9117:9117
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - jackett:/config
      - /share/Download:/downloads

  tautilli_anilist:
    image: rickdb/tautulli-plexanisync:latest
    container_name: tautilli_anilist
    restart: unless-stopped
    ports:
      - 45523:8181
    environment:
      - ANI_TOKEN=${ANI_TOKEN}
      - ANI_USERNAME=${ANI_USERNAME}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - PLEX_URL=${PLEX_URL}
      - PLEX_SECTION=${PLEX_SECTION}
      - TZ=Asia/Tokyo
    volumes:
      - tautilli_anilist:/config

volumes:
  qbittorrent:
  sonarr:
  radarr:
  bazarr:
  jackett:
  tautilli_anilist:
