services:
  pia-qbittorrent:
    image: j4ym0/pia-qbittorrent
    container_name: pia-qbittorrent
    restart: unless-stopped
    cap_add:
        - NET_ADMIN
    environment:
        - UID=1000
        - GID=100
        - REGION=Japan
        - USER=${PIA_USER}
        - PASSWORD=${PIA_PASSWORD}
        - PORT_FORWARDING=true
        - LEGACY_IPTABLES=true
        - TZ=Asia/Tokyo
    volumes:
        - /share/appdata/qbittorrent-vpn-pia:/config
        - /share/Download:/downloads
    ports:
        - 8888:8888
    networks:
      - qbittorrent-pia-vpn_default

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    depends_on:
      - pia-qbittorrent
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - sonarr:/config
      - /share/Media/Series:/tv
      - /share/Download:/downloads
    networks:
      - qbittorrent-pia-vpn_default

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    depends_on:
      - pia-qbittorrent
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - radarr:/config
      - /share/Media/Movies:/movies
      - /share/Download:/downloads
    networks:
      - qbittorrent-pia-vpn_default

  bazarr:
    image: lscr.io/linuxserver/bazarr:development
    container_name: bazarr
    restart: unless-stopped
    depends_on:
      - pia-qbittorrent
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - bazarr:/config
      - /share/Media/Movies:/movies
      - /share/Media/Series:/tv
      - /share/Download:/downloads
    networks:
      - qbittorrent-pia-vpn_default

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    depends_on:
      - pia-qbittorrent
    ports:
      - 9117:9117
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - jackett:/config
      - /share/Download:/downloads
    networks:
      - qbittorrent-pia-vpn_default
volumes:
  sonarr:
  radarr:
  bazarr:
  jackett:

networks:
  qbittorrent-pia-vpn_default:
    external: true
