services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - calibre:/config
      - /share/Media/Books:/books
    ports:
      - 24080:8080
      - 24181:8181
      - 24081:8081
    restart: unless-stopped
  komga:
    image: gotson/komga:latest
    container_name: komga
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - komga:/config
      - /share/Media/Comics/English:/manga-english
      - /share/Media/Comics/Japanese:/manga-japanese
    ports:
      - 25600:25600
    restart: unless-stopped

volumes:
  calibre:
  komga:
