services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - calibre:/config
      - /share/Media/Books:/books
    ports:
      - 24080:8080
      - 24181:8181
      - 24081:8081
    restart: unless-stopped

volumes:
  calibre:
