services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse
    volumes:
      - matrix/data:/data
    environment:
      - SYNAPSE_SERVER_NAME=matrix.davafons.com
      - SYNAPSE_REPORT_STATS=yes
    ports:
      - "8008:8008"  # Local port for testing (optional if using Traefik)
    restart: unless-stopped
    networks:

      - matrix_network

networks:
  matrix_network:
    driver: bridge

volumes:
  matrix:
